# Generated by Django 4.1.5 on 2023-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceclass',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
