# Generated by Django 4.1.5 on 2023-02-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0002_alter_attendanceclass_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 11:00', '9:00 - 11:00'), ('9:00 - 1:00', '9:00 - 1:00'), ('9:00 - 12:00', '9:00 - 12:00'), ('2:00 - 4:00', '2:00 - 4:00'), ('2:00 - 5:00', '2:00 - 5:00')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amsApp.class'),
        ),
    ]
