# Generated by Django 4.1.5 on 2023-02-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsApp', '0003_alter_assigntime_period_alter_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amsApp.dept'),
        ),
    ]
